### ISSUE TITLE
Use black for formatting

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-ml-webpage#16]
Following https://github.com/hsf-training/hsf-training-matplotlib/issues/83 and https://github.com/hsf-training/hsf-training-matplotlib/issues/88 for hsf-matplotlib, 

I think we should apply "black" formatting for the code snippets as many of the code snippets are not reader-friendly.

**Comment by klieret** [comment]
Agreed!

**Comment by amanmdesai** [comment]
I had a question. Is there a way/package to run some code on the entire episode/lesson, and it automatically updates the python parts and formats them?

**Comment by klieret** [comment]
Yes, I think https://github.com/asottile/blacken-docs does exactly that (though it might depend a bit on which markdown syntax is being used for the code inclusion).

Feel free to try with that!

**Comment by klieret** [comment]
Yeah, I'm not sure if it understands the

```
~~~
import pandas as pd # to store data as dataframe
import numpy as np # for numerical calculations such as histogramming
import matplotlib.pyplot as plt # for plotting
~~~
{: .language-python}
```

inclusions. Can you confirm that?

**Comment by amanmdesai** [comment]
Thanks for the answer. 


I tried the following test based on your question.

I tried running blacken-doc on the above test snippet which I stored in a .md file.
Nothing happens. No reformatting. It doesn't give any error. 

1. If I change the comment position by introducing a <tab>, blacken-docs will not re-format. 
2. Although it works well if we use the following: 

```python
# ~~~
import pandas as pd  # to store data as dataframe
import numpy as np  # for numerical calculations such as histogramming
import matplotlib.pyplot as plt  # for plotting
# ~~~
```

3. Using black directly on the snippet, re-formats the snippet: here is the black reformatted snippet

```python
import pandas as pd  # to store data as dataframe
import numpy as np  # for numerical calculations such as histogramming
import matplotlib.pyplot as plt  # for plotting
```

**Comment by klieret** [comment]
I assume the second thing is then a `.py` file, right?

Yes, also according to blacken-docs readme the `~~~` doesn't seem to be recognized... 

I'll try to fork the project and see if we can easily hack together a version that support this

**Comment by klieret** [comment]
I've forked blacken-docs: If you install [my version](https://github.com/klieret/blacken-docs) (by cloning the repo and then `pip install .`), blacken-docs will recognize the other syntax as well.

I'll see if I can bring it into the official version...

**Comment by klieret** [comment]
I've also just tested that and already fixed the issues in this webpage, but I'm sure our other repositories have similar problems...

**Comment by klieret** [comment]
So if you're interested in this @amanmdesai feel free to apply my modified blacken-docs there :) 

Having best-practice formatting is definitely something that we should do!

**Comment by klieret** [comment]
> I've forked blacken-docs: If you install [my version](https://github.com/klieret/blacken-docs) (by cloning the repo and then `pip install .`), blacken-docs will recognize the other syntax as well.
> 
> I'll see if I can bring it into the official version...

Forgot to push. Please version as of now :)

**Comment by klieret** [comment]
See https://github.com/asottile/blacken-docs/issues/177

**Comment by amanmdesai** [comment]
Hi, thanks for the updates. 

there seems to be one more issue: 
```python
pip install ...
 ```

does not seem to work. I see the following error on a different file. 

command :   blacken-docs 05-mplhep.md 
 Result  05-mplhep.md:27: code block parse error Cannot parse: 1:4: pip install mplhep

needs more fixing maybe?

**Comment by klieret** [comment]
I can confirm that. I've opened an issue for the matplotlib repository. `blacken-docs` worked perfectly on this one.
