### ISSUE TITLE
Confusing prerequisites

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-ml-webpage#3]
"Please read first 3 sections before coming here": But the 3 sections are already in the timetable, so this seems confusing.

I think this should be e.g. basic python (link to carpentry module etc.)

**Comment by meevans1** [comment]
Solved in commit 0eeb3f166a9338849defba19ca08e8c1a187a673.

In contrast to Luke, I'm not planning on having the first 3 sections as pre-reading, but rather as part of the workshop. I've also added a link to carpentry module.

**Comment by klieret** [comment]
Thanks @meevans1  !
