### ISSUE TITLE
Update authors file

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-ml-webpage#5]
Should have everyone who changed lesson content added to them.

**Comment by meevans1** [comment]
Fixed in commit c2ae6c93b1f809e11c1ddeb6d38c176302b014c6

**Comment by klieret** [comment]
Hi, thank you!

I didn't add content though, I only appear because of style changes, so I'll remove myself

**Comment by klieret** [comment]
Fixed in https://github.com/hsf-training/hsf-training-ml-webpage/commit/57f53af956b5e2359b9edfdd1804e0fecdce38f0

**Comment by klieret** [comment]
I also didn't see Sam in here, but I might be mistaken

**Comment by meevans1** [comment]
Sam didn't make any commits but he did contribute to content over email, so I think he deserves credit. But if the rule is only those who make commits, just let me know and I'll remove Sam.

**Comment by klieret** [comment]
No, then of course he should be in here :)
